# Generated by Django 3.2.10 on 2022-01-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='تم دفع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_atthattime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='المبلغ المتبقى وقتها'),
            preserve_default=False,
        ),
    ]
