# Generated by Django 3.2.10 on 2022-01-29 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220122_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['client__name']},
        ),
        migrations.AddField(
            model_name='orderline',
            name='skype_session_attendance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
