# Generated by Django 3.2.10 on 2022-01-30 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220129_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuiqOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('end_bill', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('remaining_atthattime', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='المبلغ المتبقى وقتها')),
                ('paid', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تم دفع')),
                ('ORDslug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='QuiqOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='الكميه')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج')),
                ('quiqorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.quiqorder')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
    ]
