# Generated by Django 3.2.10 on 2022-02-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_quiqorder_remaining_atthattime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_sold',
        ),
    ]
