# Generated by Django 3.2.10 on 2022-02-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_incomingorder_incomingorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingorder',
            name='seller',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
