# Generated by Django 3.2.10 on 2022-02-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220207_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_bill',
        ),
        migrations.RemoveField(
            model_name='quiqorder',
            name='end_bill',
        ),
    ]
