# Generated by Django 3.2.10 on 2022-01-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default='ali', max_length=50),
            preserve_default=False,
        ),
    ]
